### PR TITLE
Add new column and two service offerings

### PR DESCRIPTION
**Pull request by jasonburkert-ccpo**
### This new column will be used to store the Y/N selection for whether design services are needed
- Adds column `needs_architectural_design_services` to `Architectural Design Requirement` table

### This new group will contain two entries representing no services, one for offering type _XaaS service_ and one for offering type _Cloud support_
- Adds service offering group `NONE_APPLY`

### Two new entries in reference table `Service Offering` will be used to represent no services and belong to the new group mentioned above
- Adds two new reference data rows to `Service Offering` table

### CODE REVIEW

**Comment by jasonburkert-ccpo** [comment]
### New column
image

**Comment by jasonburkert-ccpo** [comment]
### New service offering group
image

**Comment by jasonburkert-ccpo** [comment]
### New reference data rows to represent no services
image

**Comment by jasonburkert-ccpo** [comment]
### Maintenance script for `Service Offering` table
Using this script with ServiceNow's _Scripts - Background_ feature will prune old entries that are no longer controlled via GitHub in that ServiceNow instance.  Including the two entries added by this PR, after running this script, there should be 42 total GitHub-controlled rows remaining in the reference table.

Run this as is to verify expectations, then change the ACTUALLY_DELETE_ROWS flag to true and run it again.

```
var gr = new GlideRecord('x_g_dis_atat_service_offering');
gr.addQuery('sys_id', '6b93f63787d34590ec3b777acebb35ed')
.addOrCondition('sys_id', 'c093763787d34590ec3b777acebb352d')
.addOrCondition('sys_id', 'c693f6f387d34590ec3b777acebb3588')
.addOrCondition('sys_id', '19f0bb1787274910ec3b777acebb3549')
.addOrCondition('sys_id', '7481b3c7876b0910ec3b777acebb359d')
.addOrCondition('sys_id', 'dfa1bf87876b0910ec3b777acebb35ea')
.addOrCondition('sys_id', 'fb417f87876b0910ec3b777acebb35ec')
.addOrCondition('sys_id', '08d3763787d34590ec3b777acebb35dc')
.addOrCondition('sys_id', '24735ea88799d110bc86b889cebb3588')
.addOrCondition('sys_id', '6ac3f63787d34590ec3b777acebb35cb')
.addOrCondition('sys_id', '81c3f6f387d34590ec3b777acebb358b')
.addOrCondition('sys_id', 'ae33723787d34590ec3b777acebb3535')
.addOrCondition('sys_id', '7033fef387d34590ec3b777acebb354e')
.addOrCondition('sys_id', '7903723787d34590ec3b777acebb356a')
.addOrCondition('sys_id', '0c64dfe2dba99950b1227ea5f3961921')
.addOrCondition('sys_id', 'e6efc519db79d1d0b1227ea5f39619e8');
gr.query();
gs.info('These ' + gr.getRowCount() + ' services in Service Offering table should be removed:');

while(gr.hasNext()) {
    gr.next()
    gs.info("sys_id:" + gr.sys_id + ", offering_type:" + gr.offering_type + ", service_offering_group:" + gr.service_offering_group + ", name:" + gr.name)
}
var ACTUALLY_DELETE_ROWS = false;
if (gr.getRowCount() > 0 && ACTUALLY_DELETE_ROWS) {
    gs.info('Deleting ' + gr.getRowCount() + ' rows...')
    gr.deleteMultiple();
    gs.info('Done.')
} else {
    gs.info('No rows deleted.  Set ACTUALLY_DELETE_ROWS to true to delete rows.')
}
```

**Review by ericyoungquist-ccpo — APPROVED** [review]

**Pull request merged**
