### PR TITLE
Add columns to Requirements Cost Estimate table

### PR DESCRIPTION
**Pull request by jasonburkert-ccpo**
Columns changes to `Requirements Cost Estimate` table
- Adds `Acquisition Package` reference
- Adds `Has DOW and PoP`
- Adds `Optimize/Replicate Option`
- Adds `Optimize/Replicate Estimated Values`
- Adds `Architectural Design Current Environment Option`
- Adds `Architectural Design Current Environment Estimated Values`
- Adds `Architectural Design Performance Requirements Option`
- Adds `Architectural Design Performance Requirements Estimated Values`
- Deactivates `Surge Capabilities` column
- Adds `Surge Requirement Capabilities`
- Adds `Surge Requirement Capacity`
- Adds `Contracting Office Other Charges Fee`
- Adds `Contracting Office Other Fee Percentage`
- Deactivates `Contracting Office Fee PCT` (replaced by above)
- Adds `Cost Estimate Description`
- Adds `Previous Cost Estimate Comparison Option`
- Adds `Previous Cost Estimate Comparison Percentage`

Changes to `Acquisition Package`
- Deactivates `Requirements Cost Estimate` column (replaced by reference above)

Ticket: AT-8523

### CODE REVIEW

**Comment by jasonburkert-ccpo** [comment]
Expect additional PRs for the completion of the ticket.

**Comment by jasonburkert-ccpo** [comment]
### New columns
A couple of visible columns have been deactivated.
image

### `Previous Cost Estimate Comparison Option` values

image

Supports this
image

### `Optimize/Replicate Option` values

This _Choice Set_ is referenced by a few of the columns
image

Supports questions such as this
image

**Comment by jasonburkert-ccpo** [comment]
### Diagram updates
Old columns were all disabled, this can be thought of as a new table despite existing previously

image

### Column changes

image

**Review by jeffsegal-ccpo — APPROVED** [review]
Weeee.gif

**Pull request merged**
