### PR TITLE
Training columns and Security Requirement table

### PR DESCRIPTION
**Pull request by jasonburkert-ccpo**
Changes to `Cloud Support Environment Instance` table
- Deactivates column `TS Contractor Clearance Type` (moved to new table below)
- Adds column `Training Requirement Title`
- Adds column `Training Format`
- Adds column `Training Facility Type`
- Adds column `Training Location`
- Adds column `Training Time Zone`
- Adds column `Personnel Requiring Training`
- Adds column `Can Train in Unclass Env`

Ticket: AT-8501

Adds table `Security Requirement`
- Adds column `Acquisition Package`
- Adds column `Advisory Services SECRET`
- Adds column `Advisory Services TOP SECRET`
- Adds column `Service Offering Group`
- Adds column `TS Contractor Clearance Type`

Ticket: AT-8504

- Updates Relational Model Diagram to reflect the changes

### CODE REVIEW

**Comment by jasonburkert-ccpo** [comment]
### New columns (as shown on internal form)

image

### `Training Format` values

image

### `Training Facility Type` values

image

**Comment by jasonburkert-ccpo** [comment]
### New table

image

### `TS Contractor Clearance Type` values

image

### `Service Offering Group` values

References Choice Set `service_offering_group` in `Service Offering` table

image

**Comment by jasonburkert-ccpo** [comment]
### Diagram update

image

**Review by juliusfitzhugh-ccpo — APPROVED** [review]
Looks good.

**Pull request merged**
