### PR TITLE
Create table 'Evaluation Plan' and supporting reference tables

### PR DESCRIPTION
**Pull request by jasonburkert-ccpo**
- Adds reference table `Eval Plan Differentiator`
- Adds reference table `Eval Plan Assessment Area`
- Adds reference data rows to `Eval Plan Differentiator`
- Adds reference data rows to `Eval Plan Assessment Area`
- Adds table `Evaluation Plan`
- Adds column `Acquisition Package.evaluation_plan` to connect eval plan data to the package
- Updates Relational Model Diagram to reflect the change

Ticket: AT-8128

### CODE REVIEW

**Comment by jasonburkert-ccpo** [comment]
### New table
image

### Options for Source Selection column
image

### Options for Method column
image

### New reference tables
image

image

### Data in reference tables
image

image

**Comment by jasonburkert-ccpo** [comment]
### New column
image

**Comment by jasonburkert-ccpo** [comment]
### Diagram update

image


In wider context, connected to package

image

**Review by juliusfitzhugh-ccpo — APPROVED** [review]
Looks good.

**Pull request merged**
