### PR TITLE
Add new table `Package Documents DITCO-only`; Attach generated Eval Memo documents to records in that table

### PR DESCRIPTION
**Pull request by jasonburkert-ccpo**
- Adds new table **Package Documents DITCO-only** `x_g_dis_atat_package_documents_ditco_only` (to hold Eval Memo docs)
- Improves subflow `DOCGEN: Generate Evaluation Memo` to be more resilient and transparent about failure conditions
- Adds and publishes action `UTIL: Attach Binary File to Package Documents DITCO-only`
- Changes subflow `DOCGEN: Generate Evaluation Memo` to use the new _action_ `UTIL: Attach Binary File to Package Documents DITCO-only`
- Updates `EvalMemo` script include to set `exceptionToFairOpportunity` as a boolean - This complements gap correction in https://github.com/dod-ccpo/atat-web-api/pull/1718
- Publishes subflow `DOCGEN: Generate Evaluation Memo` 
- Sets system property `x_g_dis_atat.docgen.evaluation_memo.enable` to _true_

### CODE REVIEW

**Comment by jasonburkert-ccpo** [comment]
### New table
image
Single new column `Acquisition Package` to associate a row with the package.
image
Form view including metadata and attachments
image

**Comment by jasonburkert-ccpo** [comment]
### New action
This is a copy of an existing action with slight changes.

A future refactor could replace both of these with a singular more generic implementation with more input parameters.
- `UTIL: Attach Binary File to Acquisition Package`
- `UTIL: Attach Binary File to Package Documents DITCO-only`

image

**Comment by jasonburkert-ccpo** [comment]
### Updated subflow
image

**Comment by luakim-ccpo** [comment]
Ran ` DOCGEN: Generate Evaluation Memo` to use the new action #UTIL: Attach Binary File to Package Documents DITCO-only
It's properly generating the eval memo at attached generated eval memo to DAPPS:Package Documents DITCO-only table with proper acquisiton package id
image
(verified that no duplicated records are created when I ran generating eval memo flow for multiple time)
Verified that package 450 doesn't have generated eval memo attached in the doc gen
image

**Review by luakim-ccpo — APPROVED** [review]

**Pull request merged**
