### PR TITLE
Add table IGCE Estimate

### PR DESCRIPTION
**Pull request by jasonburkert-ccpo**
Adds table `IGCE Estimate` and the following columns
- `acquisition_package`
- `selected_service_offering`
- `classification_instance`
- `cross_domain_solution`
- `contract_type`
- `title`
- `description`
- `unit_price`
- `quantity`
- `unit`
- `dow_task_number`

Deactivates these columns in `Environment Instance`
- `igce_title`
- `igce_description`
- `cost_estimate`

Deactivates these columns in `Selected Service Offering`
- `igce_title`
- `igce_description`
- `cost_estimate`

Deactivates these columns in `Classification Instance`
- `dow_task_number`
- `monthly_price`

Ticket: AT-8512

### CODE REVIEW

**Comment by jasonburkert-ccpo** [comment]
### `IGCE Estimate `table

image

**Comment by jasonburkert-ccpo** [comment]
### Diagram updates

New table

image

Deactivated columns

image

image

image

**Comment by zachclark-ccpo** [comment]
On the erd, shouldn't it be 1:M for Acquisition Package to IGCE estimate?

**Comment by zachclark-ccpo** [comment]
IGCE Table

- Change monthly_price to Unit Price
- Add Quantity/Unit 
- Add Contract field (FFP or T&M)

**Comment by juliusfitzhugh-ccpo** [comment]
Aside from the things @zachclark-ccpo pointed out I don't see any other issues.

**Comment by jasonburkert-ccpo** [comment]
> On the erd, shouldn't it be 1:M for Acquisition Package to IGCE estimate?

Good catch.  Fixed in https://github.com/dod-ccpo/atat-snow/pull/234/commits/29c26eccb46bd9f5fa52f5f53df283262cbe3943 along with similar instances

**Comment by jasonburkert-ccpo** [comment]
> IGCE Table
> 
> * Change monthly_price to Unit Price
> * Add Quantity/Unit
> * Add Contract field (FFP or T&M)

Renamed the price column and included additional columns as necessary.

**Comment by jasonburkert-ccpo** [comment]
### Contract Type values

image

### Unit values
Labels are lower case to match use on document.
image

**Review by juliusfitzhugh-ccpo — APPROVED** [review]
Looks good.

**Pull request merged**
