### PR TITLE
Define table schema for IFP

### PR DESCRIPTION
**Pull request by jasonburkert-ccpo**
## Background
A given Task Order can be incrementally funded or not.
When incrementally funded, an Incremental Funding Plan (IFP) is required.

#### Calculation
Understanding the Incremental Funding Plan (IFP) document requires knowledge of this simple calculation for funding.

**_initial amount_ + _remaining amount_ = _estimated task order value_**

- The _initial amount_ is initially provided with the task order.
- The _estimated task order value_ will be supplied by the IGCE document in future work.  We will use a temporary value for now.
- The _remaining amount_ is the _estimated task order value_ less the _initial amount_.

#### Schedule and Increments
The Incremental Funding Plan (IFP) document contains a schedule to fund non-optional CLINs under a task order.

Any _remaining amount_ can be divided into a number of quarterly funding increments.  This is the schedule.  The relative order of the increments is captured, and the quarterly descriptions are simple strings.

The sum of the amounts of all remaining amount increments should equal the _remaining amount_.  In this implementation the calculated _remaining amount_ column can be viewed as a target for the sum of the increments; any difference should be reconciled by the Mission Owner when entering IFP data.

#### Example

Initial Amount = $10,000
Remaining Amount = $30,000
Estimated Task Order Value = $40,000

Remaining Amount Increments
Order | Description | Amount
:---: | --- | ---
1 | 1 QTR FY22 | $10,000  
2 | 2 QTR FY22 | $10,000
3 | 3 QTR FY22 | $10,000

## Schema changes

Adds the following tables
- `Funding Increment`

Adds the following columns to existing tables
- `Funding Plan.Initial Amount`
- `Funding Plan.Estimated Task Order Value` (temporary until IGCE)
- `Funding Plan.Remaining Amount` (calculated)
- `Task Order.Incrementally Funded`

Adds the following references
- `Funding Plan.Remaining Amount Increments` > `Funding Increment`

Ticket: AT-7526

### CODE REVIEW

**Comment by jasonburkert-ccpo** [comment]
`Funding Plan` table

image

**Comment by jasonburkert-ccpo** [comment]
`Funding Increment` table

image

**Comment by jasonburkert-ccpo** [comment]
Funding Plan form includes informative annotations

image

**Comment by jasonburkert-ccpo** [comment]
Returned to Draft.

An IFP document is required for each incrementally funded order.  That means each row in `Funding Plan` needs a reference to a Task Order.  This requires the completion of AT-7525 first.

**Comment by jasonburkert-ccpo** [comment]
Rebased following merge of #84

**Comment by jasonburkert-ccpo** [comment]
`Task Order` table includes a reference to table `Funding Plan`
Now a given funding plan can provide the details of how to fund a specific task order.

image

**Comment by jasonburkert-ccpo** [comment]
Some of the form layout changes above...

You can see associated task orders in a related list at the bottom of the acquisition package form:

image

You can see an incremental funding plan when viewing a task order

image

Viewing a CLIN

image

**Review by robertmccardell-ccpo — APPROVED** [review]

**Pull request merged**
