### PR TITLE
Cross Domain Solution table

### PR DESCRIPTION
**Pull request by jasonburkert-ccpo**
Adds reference table `Domain Pair` - allows selection of domains to define a pair
- Adds column `Domain1`
- Adds column `Domain2`
- Adds column `Label` - a calculated value field that yields values such as _Unclassified to Secret_
- Adds column `Value` - a calculated value field that yields values such as _U_TO_S_
- Adds six data rows to reference table `Domain Pair`

Adds table `Cross Domain Solution`
- Includes column `Traffic per Domain Pair` - intended to contain stringified json w/ {<domain pair>:<monthly traffic estimate in GB>} pairs

Updates Relational Model Diagram to reflect the changes

Ticket: AT-8390

### CODE REVIEW

**Comment by jasonburkert-ccpo** [comment]
### New reference table
image

### Reference data rows
Reference table `Domain Pairs` contains six rows, one for each direction between the three domain nodes.  Each row's sys_id can be paired with traffic estimate in GB/month.  Reference table has usable calculated Label and Value columns.

image

image

**Comment by jasonburkert-ccpo** [comment]
### `Cross Domain Solution` table
image

### Sample internal form
MicrosoftTeams-image (2)

**Comment by jasonburkert-ccpo** [comment]
### Diagram updates

image

Reference table
image

**Comment by jasonburkert-ccpo** [comment]
FYI Might add a columns to `Cross Domain Solution` for AT-8512, still assessing.  But don't hesitate to merge this since those will be additions.

**Review by juliusfitzhugh-ccpo — APPROVED** [review]
Looks good.

**Comment by juliusfitzhugh-ccpo** [comment]
Merging so there is a clean branch for the next tickets.

**Pull request merged**
