### PR TITLE
Feature/at 9061

### PR DESCRIPTION
**Pull request by torinharthcock-ccpo**
Updated IFP script to use the costEstimate function to calculate base year subtotal.

### CODE REVIEW

**Comment by torinharthcock-ccpo** [comment]
image

image

**Comment by luakim-ccpo** [comment]
@torinharthcock-ccpo  This only grab the value for DITCO user. if the user is non-ditco estimated base year value should be Subtotal for base period (no Surge) PLUS External Ordering Agency Fee (1%)

**Comment by torinharthcock-ccpo** [comment]
> @torinharthcock-ccpo This only grab the value for DITCO user. if the user is non-ditco estimated base year value should be Subtotal for base period (no Surge) PLUS External Ordering Agency Fee (1%)

According to Devonte, the costEstimate function calculates the subtotal as including the external Ordering Agency fee. There's been some issues with the costEstimate function for non-Ditco users but my understanding from Tom is that that would be addressed in a separate ticket.

**Comment by luakim-ccpo** [comment]
Documenting comment made to Torin in Slack
- DITCO user - subtotal of all CLINS for base year without surge
- Non-DITCO user - (subtotal of all CLINS for base year without surge) * 1.01 [adding 1% of subtotal]

With this, you are keeping your base year subtotal for DITCO user. 
However, for non-ditco user, you have to multiply by 1% to include external agency fee. 
you are grabbing the right data from cost estimate api, you just need extra logic for non-ditco user

**Comment by luakim-ccpo** [comment]
image

**Review by luakim-ccpo — APPROVED** [review]

**Pull request merged**
