### PR TITLE
Schema changes for Current Environment data

### PR DESCRIPTION
**Pull request by jasonburkert-ccpo**
- Updates columns of `Environment Instance`
- Adds table `Current Environment Instance` (extends `Environment Instance`)
- Updates columns of `Current Environment`
- Adds table `Database Environment Instance` (extends `Environment Instance`)
- Removes table `Current Environment System Documentation` which has been replaced by `Current Environment.system_documentation`
- Removes table `Current Environment Migration Documentation` which has been replaced by `Current Environment.migration_documentation`
- Updates diagrams
  - added new tables
  - updates existing tables
  - added target table to descriptions for FK columns (Reference or List type)
- Updates form layouts
  - base properties (from base table) remain in same place
  - extended properties on own tab

Builds on #195 to complete
Ticket: AT-8246

### CODE REVIEW

**Comment by jasonburkert-ccpo** [comment]
### `Environment Instance`

image

### Updated choice options

**Storage Unit**
Referenced by next two entries below
image

**Data Egress Monthly Unit**
image

**Memory Unit**
image

**Instance Location**
image

**Performance Tier**
image

**Pricing Model**
image

**Storage Type**
image

**Comment by jasonburkert-ccpo** [comment]
### Current Environment Instance

image
image
image

### Choice options
**Current Usage Description**
image

**Operating Environment**
image

**Operating Type**
image

**Comment by jasonburkert-ccpo** [comment]
### `Current Environment`

image
image

### Updated choice options

**Current Environment Replicated Optimized**
image

**Env Location**
image

**Comment by jasonburkert-ccpo** [comment]
### `Database Environment Instance`
Extends `Environment Instance`

image
image

### Choice options

**Database Licensing**
image

**Database Type**
image

**Comment by jasonburkert-ccpo** [comment]
### New and updated tables

image

**Comment by jasonburkert-ccpo** [comment]
### Form layouts

**Environment Instance**
image

**Current Environment Instance**
Extended properties in own tab
image

**Review by juliusfitzhugh-ccpo — COMMENTED** [review]
This was a really tricky one since there was a lot of old/new information to go through along with incoming changes. Based on what I can see the `Current Environment` is captured, nice work.

A few things I found that I wasn't sure about
- Does `additional_information` belong on `Environment Instance`?
  - Not sure if I over looked it or if it's not found in the tables I checked
  - Also, it appears twice under the `CURRENT-ENVIRONMENT` section schema in the ticket, but has conflicting notes (add vs remove).
- I noticed the `Compute Instance` and `Storage instance` schemas were not used, is this because `Environment Instance` captures that information? 
- The `current_environment_exists` column in `Current Environment` might need to be updated after merging, since it appeared as if the column was still `True/False` type on my PDI (known error that happens when you delete a column and rename it with the same name but as a different type).

**Comment by jasonburkert-ccpo** [comment]
> This was a really tricky one since there was a lot of old/new information to go through along with incoming changes. Based on what I can see the `Current Environment` is captured, nice work.

I relied heavily on the UI Team's data object.

> 
> A few things I found that I wasn't sure about
> 
> * Does `additional_information` belong on `Environment Instance`?
>   
>   * Not sure if I over looked it or if it's not found in the tables I checked
>   * Also, it appears twice under the `CURRENT-ENVIRONMENT` section schema in the ticket, but has conflicting notes (add vs remove).

Not sure.  I'll double-check.

> * I noticed the `Compute Instance` and `Storage instance` schemas were not used, is this because `Environment Instance` captures that information?

I anticipate adding them later in other PRs and that they'll work like `Current instance`.  Simply haven't gotten there yet.  See the need, but unsure of specific columns at the moment.

> * The `current_environment_exists` column in `Current Environment` might need to be updated after merging, since it appeared as if the column was still `True/False` type on my PDI (known error that happens when you delete a column and rename it with the same name but as a different type).

Good reminder.  Might need to remove these tables prior to applying updates from GitHub on a given environment.

**Comment by jasonburkert-ccpo** [comment]
> * I noticed the `Compute Instance` and `Storage instance` schemas were not used, is this because `Environment Instance` captures that information?

Update after speaking with @tonysumner-ccpo: Shouldn't need `Storage Instance`.  `Compute Instance` is still to come.

**Comment by jasonburkert-ccpo** [comment]
> * Does `additional_information` belong on `Environment Instance`?

Per @ericyoungquist-ccpo and @ajaynalamala-ccpo this belongs in `Current Environment Instance`.  The ticket had conflicting information due to my mistake.  I've updated the ticket and fixed the implementation and diagram in https://github.com/dod-ccpo/atat-snow/pull/196/commits/c3ea6dafc389e174d1fb84235d631acb92584643 and https://github.com/dod-ccpo/atat-snow/pull/196/commits/81c0d0bf1c5d0e7550718c86123f31ee02478c1e

**Review by juliusfitzhugh-ccpo — APPROVED** [review]
Thanks for answering my questions and updating `additional_information`. Looks good.

**Pull request merged**
