### PR TITLE
Feature/at 8988

### PR DESCRIPTION
**Pull request by torinharthcock-ccpo**
Created a new flow that will send an email to all mission owners when a package has been completed by a contributor. Should not send out an email when a mission owner finishes the package.

### CODE REVIEW

**Comment by torinharthcock-ccpo** [comment]
image

image

Flow should be triggered by completing a package by any contributor that's not a mission owner.

**Comment by luakim-ccpo** [comment]
@torinharthcock-ccpo @tonysumner-ccpo 
I thought based on parking lot session, we are going to trigger this flow when the contributor clicks "Continue" button from the UI. 
Right now, the email is triggered when the contributor create/updated DAPPS:Package Documents Signed 
This could lead Mission Owner (MO) receiving multiple emails as Contributor is uploading the signed document one at a time, sending email each to MO as signed document is being uploaded and record is being updated

**Comment by luakim-ccpo** [comment]
image
Based on ticket AC:

Email context:
Your JWCC requirements package is now complete and ready to submit

All signed documents have been uploaded to “Acquisition package title” within the DISA Acquisition Package Preparation System (DAPPS). As the owner, you are responsible for certifying and submitting this package to DITCO for processing.

Access the package from your dashboard:: https://services.disa.mil/atat-dapps

**Comment by luakim-ccpo** [comment]
also don't include watermark
image

To be consistent with your email action, I would Change the flow name to be: 
CONTRIB: Package is Ready to Be Submitted
image

**Comment by luakim-ccpo** [comment]
Just to document the conversation, this email will be triggered by UI https://ccpo.atlassian.net/browse/AT-9420

**Review by luakim-ccpo — APPROVED** [review]

**Pull request merged**
