### PR TITLE
Update Flows to use Period Table

### PR DESCRIPTION
**Pull request by zachclark-ccpo**
## Overview
This ticket has evolved into rewriting the custom script on the **DocuSign Set Field Value** action to properly handle the new data structure created in [AT-7309](https://ccpo.atlassian.net/browse/AT-7309)
image
Following guidance of https://dodccpo.slack.com/archives/C01HP693C7K/p1652466991914719?thread_ts=1652464564.227569&cid=C01HP693C7K to improve the implementation of the script.

### Existing Script
```
// Example output
// Base period: 1 Year
// Option 1 period: 3 Week(s)
var raw = fd_data.trigger.current.period_of_performance.base_and_options;
var keyArray = Object.keys(raw);
var out = '';
for (key in keyArray) {
  var periodObj = JSON.parse(raw[keyArray[key]]);
  var duration = periodObj['duration'];
  var unitOfTime = periodObj['unitOfTime'];
  out += keyArray[key] + ' period: ' + duration + ' ' + unitOfTime;
  if (key != (keyArray.length - 1)) {
    out += ', ';
  }
}
return out;
```
### New Script (in progress)
```
// Retrieve basePeriod information
// Clean this up into a single line
var out = '';
var basePeriod = fd_data.trigger.current.period_of_performance.base_period;
out += basePeriod.period_type.getDisplayValue() + ' period: ' + basePeriod.period_unit_count.getDisplayValue() + ' ' + basePeriod.period_unit.getDisplayValue(); 

var list = fd_data.trigger.current.period_of_performance.option_periods;
// list output is "value":"1ff296f1872b0510bc86b889cebb3537,b30396f1872b0510bc86b889cebb353c"
// split into an array, to look up each record and set the values
var arrayOps = list.split(',');
// set up glide record to query based on the value
var gr = new GlideRecord('x_g_dis_atat_period');
for (var i=0; i < arrayOps.length; i++) {
gr.get(arrayOps[i]);
if(gr.period_type == 'OPTION'){
 out += ', ' + gr.period_type.getDisplayValue() + ' ' + gr.option_order.getDisplayValue() + ' period: ' + gr.period_unit_count.getDisplayValue() + ' ' + gr.period_unit.getDisplayValue();
}

}


return out;
```

### CODE REVIEW

**Comment by zachclark-ccpo** [comment]
image
Getting closer to the desired solution.

**Comment by zachclark-ccpo** [comment]
Going to wait for the dev issues to be resolved before merging. The script is updated and working, based on the 1:30 meeting with Jason and Julius it meets ticket requirements.

**Comment by kylelaker-ccpo** [comment]
Can we break the formatting into a function? If so, maybe do:

```js
function formatPeriod(periodName, period) {
  return periodName + period.period_unit_count.getDisplayValue() + ' ' + period.period_unit.getDisplayValue();
}

// Format the base Period text as "Base period: N <Day(s) | Month(s) | Year(s)>"
function formatBasePeriod(period) {
  return formatPeriod(basePeriod.period_type.getDisplayValue + ' period: ', period)
}

// Format the option Period text as "Option period M: N <Days(s) | Month(s) | Year(s)>"
function formatOptionPeriod(period) {
  return formatPeriod(period.period_type.getDisplayValue() + ' period ' + period.get_option_order.getDisplayValue() + ': ', period);
}

// Retrieve basePeriod information
var formattedText = formatBasePeriod(fd_data.trigger.current.period_of_performance.base_period);

// The option_periods on the record is a formatted like "ID1,ID2". Those IDs can then
// be looked up on the atat_period GlideRecord to fetch the full object data.
var optionPeriodIds = fd_data.trigger.current.period_of_performance.option_periods.split(',');
var gr = new GlideRecord('x_g_dis_atat_period');
for (var i = 0; i < optionPeriodIds.length; i++) {
  gr.get(optionPeriodIds[i]);
  if (gr.period_type !== 'OPTION') {
   // Skip base period
   continue;
  }
  formattedText += ', ';
  formattedText += formatOptionPeriod(gr);
}


return formattedText;
```

If we can't then I'd like to at least really commit to `+=`ing everything:

```js
var basePeriod = fd_data.trigger.current.period_of_performance.base_period;
var formattedText = '';
// Format the base Period text as "Base period: N <Day(s) | Month(s) | Year(s)>"
formattedText += basePeriod.period_type.getDisplayValue();
formattedText += ' period: ';
formattedText += period.period_unit_count.getDisplayValue();
formattedText += ' ';
formattedText += period.period_unit.getDisplayValue();

// The option_periods on the record is a formatted like "ID1,ID2". Those IDs can then
// be looked up on the atat_period GlideRecord to fetch the full object data.
var optionPeriodIds = fd_data.trigger.current.period_of_performance.option_periods.split(',');
for (var i = 0; i < optionPeriodIds.length; i++) {
  gr.get(optionPeriodIds[i]);
  if (gr.period_type !== 'OPTION') {
    // Skip base period
    continue;
  }
  // Format the option Period text as "Option period M: N <Days(s) | Month(s) | Year(s)>"
  formattedText += ', ';
  formattedText += gr.period_type.getDisplayValue();
  formattedText += ' period ',
  formattedText += gr.option_order.getDisplayValue();
  formattedText += ': ';
  formattedText += gr.period_unit_count.getDisplayValue();
  formattedText += ' ';
  formattedText += gr.period_unit.getDisplayValue();
}
return formattedText;
```

This also changes the behavior slightly so that you get "Option period 1: 6 month(s)".

**Comment by jasonburkert-ccpo** [comment]
The advice above looks like a good idea.  After that I think this will be ready to merge.

**Pull request closed without merging**
