### PR TITLE
Add table Classified Information Type

### PR DESCRIPTION
**Pull request by jasonburkert-ccpo**
- Adds table `Classified Information Type`
- Adds twelve rows of reference data
- Adds List column to `Classification Instance` to store selections
- Adds List column to `Environment Instance` to store selections
- Updates Relational Model Diagram to reflect the change

Table will provide reference data to present screens such as this one

image

Ticket: AT-8410

### CODE REVIEW

**Comment by jasonburkert-ccpo** [comment]
### New table

image

### Reference data rows

image

**Comment by jasonburkert-ccpo** [comment]
### New List columns

image

image

**Comment by jasonburkert-ccpo** [comment]
### Diagram update

image

**Review by juliusfitzhugh-ccpo — APPROVED** [review]
Looks good.

**Pull request merged**
