### PR TITLE
Add column 'Provisioning Request Date' to Portfolio and Operator tables

### PR DESCRIPTION
**Pull request by jasonburkert-ccpo**
- Adds column `Portfolio.provisioning_request_date`
- Adds column `Operator.provisioning_request_date`
- Adds column `Portfolio.provisioning_failure_cause`
- Adjusts form and list layouts for `Portfolio` and `Operator`

Ticket: AT-7988

### CODE REVIEW

**Comment by jasonburkert-ccpo** [comment]
### `Portfolio` form
Added fields for new columns.  Renamed `CSP` tab to `Provisioning`.  Added `Operators` to related lists display.  `Pending Operators`, once provisioned, would be shown in the `Operators` list.

image

**Comment by jasonburkert-ccpo** [comment]
### `Operator` form
Added field for new column.

image

**Comment by jasonburkert-ccpo** [comment]
In retrospect, these two tables could have extended a table such as `Provisionable Entity` that contained the CSP and provisioning related columns.

**Comment by jasonburkert-ccpo** [comment]
While not specified in the ticket, noticed lack of failure cause in `Portfolio` and decided to add it here for symmetry with `Operator`

**Review by juliusfitzhugh-ccpo — COMMENTED** [review]
Nice touch with the `Related List` for operators! The ticket ACs are satisfied with this PR. Below are some related things that came to mind while reviewing.

It seems that `Pending Operators` were removed from the `Acquisition Package` in ticket 7894, so made me start thinking about operators. A few questions that came to mind:
- How are `Pending Operators` getting added in the `Portfolio`?
- Where/when will `Operators` be added to the `Portfolio`? 

The `ATAT Acquisition Package Submission` flow has to be updated as well since it used the original `Pending Operators` before things changed. 
PendingOperators

**Comment by jasonburkert-ccpo** [comment]
> How are Pending Operators getting added in the Portfolio?

@juliusfitzhugh-ccpo Thanks for raising this issue.  Sounds like 7894 / #143 inadvertently broke the list of operators `Acquisition Package.operators` that was feeding the bootstrapping of Portfolio.pending_operators at package submission.
Will reintroduce that and call it `pending_operators` in another ticket.

> Where/when will Operators be added to the Portfolio?

For initial Portfolio provisioning with operators, I believe this is done, but later addition of operators has yet to be implemented.  Intent is for `Portfolio.Pending Operators` to be processed regularly and a positive CSP response would result in an entry in `Operator` table with `provisioned` = true.

**Review by juliusfitzhugh-ccpo — APPROVED** [review]
@jasonburkert-ccpo thanks for answering my questions, approving PR.

**Pull request merged**
