### PR TITLE
Add Months in Period column to Period table

### PR DESCRIPTION
**Pull request by jasonburkert-ccpo**
IGCE document requires frequent calculations based on the number of months in a selected period (or in some cases using that figure as an upper limit).

- Adds `Months in Period` column to `Period` table - a calculated value (rounds up to the nearest whole month)
  - The rounding means that both 1 day and 1 week periods evaluate to 1 month in the period
  - 0 days/weeks/months/years returns 0 months in the period
  - any error or unexpected condition returns -1

Ticket: AT-8548

### CODE REVIEW

**Comment by jasonburkert-ccpo** [comment]
### New column implementation

image

```
function calculateMonths(unit_count, unit) {
    var ERROR_VALUE = -1;
    //check parameter types
    if (typeof unit_count !== "number") {
        gs.debug("Function calculateMonths accepts a number for parameter unit_count.  Received " + typeof unit_count + " instead.");
    }
    if (typeof unit !== "string") {
        gs.debug("Function calculateMonths accepts a string for parameter unit.  Received " + typeof unit + " instead.");
    }
    //ensure unit count is greater than zero
    if (unit_count < 0) {
        gs.debug("Parameter unit_count for function calculateMonths is expected to be greater than 0.  Received " + unit_count);
        return ERROR_VALUE;
    }
    //perform the calcuation
    switch (unit) {
        case "YEAR":
            var MONTHS_PER_YEAR = 12;
            return unit_count * MONTHS_PER_YEAR;
        case "MONTH":
            return unit_count;
        case "WEEK":
            /* Average weeks in a month = 4.345 ( X weeks / 4.345 = Y months) */
            /* Ex 1: 36 weeks (36/4.345 = 8.285 --> Round up to 9 months) */
            /* Ex 2: 1 week (1/4.345 = 0.230 --> Round up to 1 month) */
            var AVG_WEEKS_PER_MONTH = 4.345;
            return Math.ceil(unit_count / AVG_WEEKS_PER_MONTH);
        case "DAY":
            /* Average days in a month = 30.4167  ( X days / 30.4167 = Y months) */
            /* Ex 1: 252 days (259/30.4167 = 8.284 --> Round up to 9 months) */
            /* Ex 2: 1 day (1/30.4167 = 0.032 --> Round up to 1 month) */
            var AVG_DAYS_PER_MONTH = 30.4167;
            return Math.ceil(unit_count / AVG_DAYS_PER_MONTH);
        default:
            gs.debug("Parameter unit for function calculateMonths is expected to be one of YEAR/MONTH/WEEK/DAY.  Received " + unit);
            return ERROR_VALUE;
    }
}

(function calculatedFieldValue(current) {
    return calculateMonths(current.period_unit_count, current.period_unit.toString());
})(current);
```

### Sample period list with new column

image

**Comment by zachclark-ccpo** [comment]
Not sure if you have seen `monthsInPeriod` Script Include.
Function for it is here: 
```
function monthsInPeriod(unit, unit_count) {
	var months_in_period;
	if (unit == "DAY"){
		// months = days × 0.032855
		months_in_period = Math.ceil(parseInt(unit_count * 0.032855));
	}
	if (unit == "WEEK"){
		// months = weeks × 0.229984
		months_in_period = Math.ceil(parseInt(unit_count * 0.229984));
	}
	if (unit == "MONTH"){
		// months = months
		months_in_period = unit_count;
	}
	if (unit == "YEAR"){
		// months = years × 12
		months_in_period = parseInt(unit_count * 12);
	}
	return months_in_period;
	
}
```

**Comment by jasonburkert-ccpo** [comment]
> Not sure if you have seen `monthsInPeriod` Script Include. Function for it is here:
> 
> ```
> function monthsInPeriod(unit, unit_count) {
> 	var months_in_period;
> 	if (unit == "DAY"){
> 		// months = days × 0.032855
> 		months_in_period = Math.ceil(parseInt(unit_count * 0.032855));
> 	}
> 	if (unit == "WEEK"){
> 		// months = weeks × 0.229984
> 		months_in_period = Math.ceil(parseInt(unit_count * 0.229984));
> 	}
> 	if (unit == "MONTH"){
> 		// months = months
> 		months_in_period = unit_count;
> 	}
> 	if (unit == "YEAR"){
> 		// months = years × 12
> 		months_in_period = parseInt(unit_count * 12);
> 	}
> 	return months_in_period;
> 	
> }
> ```

No. I had not seen that.  Looks somehow familiar.

**Comment by jasonburkert-ccpo** [comment]
We're going to call this tech debt and do it later.  Implementing a unified solution in the ServiceNow database can replace the UI and document generation implementations of this calculation in the future.

**Pull request closed without merging**
