### PR TITLE
Add table Compute Environment Instance

### PR DESCRIPTION
**Pull request by jasonburkert-ccpo**
- Adds table `Compute Environment Instance` (extends `Environment Instance`)
- Updates Relational Model Diagram to reflect the change

Ticket: AT-8409

### CODE REVIEW

**Comment by jasonburkert-ccpo** [comment]
### New table
image

### Form layout
Extended properties on own tab

image

**Comment by jasonburkert-ccpo** [comment]
### Environment Type options
image

### Operating Environment options
image

**Review by juliusfitzhugh-ccpo — COMMENTED** [review]
Looks good, do you plan to update the `diagrams.md` in this PR?

**Comment by jasonburkert-ccpo** [comment]
> Looks good, do you plan to update the `diagrams.md` in this PR?

Yes. Thank you for the reminder.

**Comment by jasonburkert-ccpo** [comment]
### Diagram update
image

**Comment by jasonburkert-ccpo** [comment]
> Looks good, do you plan to update the `diagrams.md` in this PR?

Diagram updated in https://github.com/dod-ccpo/atat-snow/pull/205/commits/bf439dc875ff222f8bd5af3d742a93ec9c8a3e02

**Review by juliusfitzhugh-ccpo — APPROVED** [review]

**Pull request merged**
