### PR TITLE
DOW schema changes

### PR DESCRIPTION
**Pull request by jasonburkert-ccpo**
- Adds table `Architectural Design Requirement`
- Adds table `Cloud Support Environment Instance` (extends `Environment Instance`)
- Removes columns from `Current Environment` (use `Architectural Design Requirement` instead)
- Adds column `Architectural Design Requirement` to `Current Environment`
- Adds column `Architectural Design Requirement` to `Selected Service Offering`
- Removes column `Estimated Environment Instances` from `Current Environment`
- Replaces/changes two _Choice_ columns in `Current Environment Instance` to references options already defined in `Compute Environment Instance`
- Updates Relational Model Diagram to reflect the change

Ticket: AT-8477

### CODE REVIEW

**Comment by jasonburkert-ccpo** [comment]
Table `Cloud Support Environment Instance` requires additional columns, but the above is ready for review.

**Comment by jasonburkert-ccpo** [comment]
### New table Architectural Design Requirement

image

image

### New table Cloud Support Environment Instance

image
image

image

**Comment by jasonburkert-ccpo** [comment]
### Replaced/Updated columns (now referencing options already defined in `Compute Environment Instance`)
image

**Comment by jasonburkert-ccpo** [comment]
### Wider context diagram
image

**Comment by zachclark-ccpo** [comment]
Suggested changes:
- Compute Environment Instance should have `monthly_price` or `unit_price`
- Environment Instance should have have `monthly_price` or `unit_price`

**Comment by zachclark-ccpo** [comment]
image
Can you have more than one Architectural Design Requirement?

**Comment by jasonburkert-ccpo** [comment]
> Suggested changes:
> 
> * Compute Environment Instance should have `monthly_price` or `unit_price`
> * Environment Instance should have have `monthly_price` or `unit_price`

Are you suggesting one or the other, but not both?

**Comment by zachclark-ccpo** [comment]
> > Suggested changes:
> > 
> > * Compute Environment Instance should have `monthly_price` or `unit_price`
> > * Environment Instance should have have `monthly_price` or `unit_price`
> 
> Are you suggesting one or the other, but not both?

For IGCE they slashed monthly_price in favor of unit_price, but if you change it to unit_price you may aswell change it in
the existing tables.

**Comment by jasonburkert-ccpo** [comment]
> image Can you have more than one Architectural Design Requirement? If so this should be a list of references

In that case you might have more than one Selected Service Offering.

**Review by zachclark-ccpo — APPROVED** [review]
Questions were addressed, I am able to create records in the new tables and see the changes in my PDI.

**Pull request merged**
