### PR TITLE
Improve table Operator

### PR DESCRIPTION
**Pull request by jasonburkert-ccpo**
- Adds column `x_g_dis_atat_operator.portfolio`
- Adds column `x_g_dis_atat_operator.provisioned_date`
- Adds column `x_g_dis_atat_operator.provisioning_failure_cause`
- Adds column `x_g_dis_atat_operator.added_by`
  - this is a calculated value column that shows display value of `sys_created_by`
- Deletes column `x_g_dis_atat_operator.acquisition_package`
- Deletes column `x_g_dis_atat_acquisition_package.operators`
- Adjusts list and form layouts for `Operator`
- Adjusts list and form layouts for `Acquisition Package`

Ticket: AT-7894

### CODE REVIEW

**Comment by jasonburkert-ccpo** [comment]
### `Operator` table

image

### Operator list

image

### Operator form

image

image

**Comment by jasonburkert-ccpo** [comment]
### Acquisition Package list

image

### Acquisition Package form

image

image

**Review by juliusfitzhugh-ccpo — APPROVED** [review]
I like what you did with the forms layout and organization in the acquisition package. Update to the tables look good.

**Comment by jasonburkert-ccpo** [comment]
> I like what you did with the forms layout and organization in the acquisition package. Update to the tables look good.

Thanks.  Glad it was well received.  The package form was a bit unruly before.

**Pull request merged**
