### PR TITLE
DOW schema changes

### PR DESCRIPTION
**Pull request by jasonburkert-ccpo**
- Adds `Acquisition Package` to `Selected Service Offering`
- Deactivates `Selected Service Offerings` in `Acquisition Package`; replaced by the above
- Adds `Usage Description` to `Environment Instance`
- Adds `Network Performance` to `Database Environment Instance`

Ticket: AT-8480

- Adds columns `Cost Estimate`, `IGCE Title`, `IGCE Description` to `Selected Service Offering`
- Adds columns `Cost Estimate`, `IGCE Title`, `IGCE Description` to `Environment Instance`

Ticket: AT-8490

- Updates Relational Model Diagram to reflect the changes

### CODE REVIEW

**Comment by jasonburkert-ccpo** [comment]
#### New columns
image

image

image

**Comment by jasonburkert-ccpo** [comment]
### Diagram updates

image

image

image

**Review by juliusfitzhugh-ccpo — APPROVED** [review]
Looks good. I know it was mentioned that the `acq pkg` column wouldn't be added to the `Classification Instance` table, is that still true?

**Comment by jasonburkert-ccpo** [comment]
> Looks good. I know it was mentioned that the `acq pkg` column wouldn't be added to the `Classification Instance` table, is that still true?

Yeah, that's still the case, so I struck it in the description of AT-8480

**Pull request merged**
