### PR TITLE
Add columns to 'Environment Instance'

### PR DESCRIPTION
**Pull request by jasonburkert-ccpo**
Adds columns to `Environment Instance`
- `acquisition_package`
- `operating_system_licensing`
- `anticipated_need_or_usage`

Updates Relational Model Diagram to reflect the change

Ticket: AT-8476

### CODE REVIEW

**Comment by jasonburkert-ccpo** [comment]
### New columns
image

**Comment by jasonburkert-ccpo** [comment]
### Diagram update
image

In wider context
image

**Review by zachclark-ccpo — APPROVED** [review]

**Review by juliusfitzhugh-ccpo — APPROVED** [review]
Looks good. Minor consideration, not blocking. Should the `Database Environment Instance` table use the choices from the new `Operating System Licensing` choices provided in `Environment Instance`?

**Comment by jasonburkert-ccpo** [comment]
> Looks good. Minor consideration, not blocking. Should the `Database Environment Instance` table use the choices from the new `Operating System Licensing` choices provided in `Environment Instance`?

Ideally, yes.  But due to urgency I wanted to avoid changing existing columns, so opted to duplicate the values.

**Pull request merged**
