### PR TITLE
Create SNOW subflow ATAT Generate Description of Work and other artifacts

### PR DESCRIPTION
**Pull request by zachclark-ccpo**
# Overview
This PR and branch represent a cleaned version of the work started in [feature/AT-7344](https://github.com/dod-ccpo/atat-snow/compare/develop...feature/AT-7344), meaning there are no Administrator commits.

## SNOW Artifacts
This PR creates the following ServiceNow artifacts:

- **ATAT Generate Description of Work** (Subflow)
- **ATAT Secure POST Request** (Action)
- **Attach Binary File to Acquisition Package** (Action)

This PR also modifies the **Gather DescriptionOfWork Data** (Action) to modify the schema to match the changes in https://github.com/dod-ccpo/atat-web-api/pull/932

## Testing Process
1. Using your PDI, create a valid acquisition package (fill out all fields).
2. Set up an AWS credential in SNOW (this will require atat-sandbox-admin to retrieve the key value pair from Secrets Manager)
3. Open **ATAT Generate Description of Work** (Subflow) in Flow Designer, and hit Test (in the top right of the screen)
image
4. Open the results, all steps should be completed 
image
5. Check the Acquisition Package record that you specified in the test, it should now have _Description of Work.pdf_ as an attachment 
image
6. Download the attachment, ensure that it opens 
image

## Tickets
[AT-7344](https://ccpo.atlassian.net/browse/AT-7344)
[AT-7516](https://ccpo.atlassian.net/browse/AT-7516)

### CODE REVIEW

**Comment by jasonburkert-ccpo** [comment]
Thanks for taking the time to make a clean PR with no administrator commits.

**Review by juliusfitzhugh-ccpo — APPROVED** [review]
Nice work, this was really some nice work done to get things work!

**Comment by jasonburkert-ccpo** [comment]
Really great to see PDF content attached after testing the subflow!
image

**Comment by jasonburkert-ccpo** [comment]
@zachclark-ccpo Nice effort on this core functionality!
@juliusfitzhugh-ccpo Thanks for the last minute error handling tweak.

**Review by jasonburkert-ccpo — APPROVED** [review]

**Comment by juliusfitzhugh-ccpo** [comment]
Added some basic error handling to avoid attachment if the request fails. 
- Updated `ATAT Secure POST Request` to error if 200 not
Screen Shot 2022-06-10 at 8 19 44 PM

- Turned on `Error Handler` on `ATAT Generate Description of Work` subflow with a log
Screen Shot 2022-06-10 at 8 44 00 PM
Screen Shot 2022-06-10 at 8 43 02 PM
Screen Shot 2022-06-10 at 8 43 14 PM
Screen Shot 2022-06-10 at 8 42 44 PM

**Pull request merged**
