### PR TITLE
Set provisioning dates for Portfolio

### PR DESCRIPTION
**Pull request by jasonburkert-ccpo**
This began as updates to provisioning request dates and provisioned dates, but grew to include other necessary changes such as updating status values and provisioning flags.  Also included is an update to the provisioning job payload due to recent changes in the HOTH API.

Updates to `provisioning_request_date` fields occur in flow `Queue Initial Portfolio Provisioning Job`

Updates to `provisioned_date` fields occur in flow `ATAT Provisioning Request` indirectly via a new flow action named `Update Portfolio to Provisioned`.

Changes to flow `Queue Initial Portfolio Provisioning Job`:
- sets `Portfolio.portfolio_status` to _Processing_
- sets `Portfolio.provisioning_request_date`
- sets `Operator.provisioning_request_date`
- changes provisioning job creation to place `fundingSources` and `operators` inside the `payload`
- updates trigger to ensure required inputs are available
- note: `Portfolio.provisioned` is initially _false_ by column default
- note: `Operator.provisioned` is initially _false_ by column default

Changes to flow `ATAT Provisioning Request`:
- moved some steps to new action `Update Portfolio to Provisioned` to be used later when CSP provisioning results are consumed

Adds action `Update Portfolio to Provisioned`, which does the following:
- updates `Portfolio.provisioned` to _true_
- sets `Portfolio.provisioned_date`
- updates portfolio operators `Operator.provisioned` to _true_
- sets portfolio operators `Operator.provisioned_date`
- updates `Portfolio.Pending Operators` to _null_

Changes to action `HOTH API POST Request`:
- removes unused inputs

Replaces #159

Ticket: AT-7992

### CODE REVIEW

**Comment by jasonburkert-ccpo** [comment]
### Updated payload for provisioning job

image

```
var portfolio = fd_data.trigger.current;
var OPERATOR_TABLE = "x_g_dis_atat_operator";
var CLIN_TABLE = "x_g_dis_atat_clin";
return {
  jobId: gs.generateGUID(),
  userId: portfolio.portfolio_managers.split(",")[0],
  operationType: "ADD_PORTFOLIO",
  targetCsp: {
    name: portfolio.csp.name.toString(),
    // uri and network properties are deprecated
  },
  payload: {
    name: portfolio.name.toString(),
    operators: portfolio.operators.split(",").map(function(operatorId) {
      var record = new GlideRecord(OPERATOR_TABLE);
      record.get(operatorId);
      return {
        email: record.email.toString(),
        dodId: record.dod_id.toString(),
        needsReset: record.needs_reset.toString(),
      };
    }),
    fundingSources: portfolio.active_task_order.clins.split(",").map(function(sysId) {
      var record = new GlideRecord(CLIN_TABLE);
      record.get(sysId);
      return {
        taskOrderNumber: portfolio.active_task_order.task_order_number.toString(),
        clin: record.clin_number.toString(),
        popStartDate: record.pop_start_date.toString(),
        popEndDate: record.pop_end_date.toString(),
      };
    }),
  },
};
```

**Comment by jasonburkert-ccpo** [comment]
### Updating Portfolio record

image

### Updating Operator records

image

**Comment by jasonburkert-ccpo** [comment]
### Updating Operator Records (upon successful provisioning)

image

**Comment by jasonburkert-ccpo** [comment]
### Updating Provisioning Job Record

image

**Comment by jasonburkert-ccpo** [comment]
### Updated trigger

image

**Comment by jasonburkert-ccpo** [comment]
### The new action

image

image

Logs similar to the following
image


### Invoking the new action

Moved all portfolio and operator updates into the new Action.  The remainder of this flow manages the job and logs the outcome.
image

**Review by juliusfitzhugh-ccpo — CHANGES_REQUESTED** [review]
Nice work, this captures a lot of needed updates for provisioning requests. I like the `Update Portfolio to Provisioned` action, but I think this needs to be moved downstream where we poll messages from the provisioning job queue (not yet implemented). Everything else looks good and works as expected, including the request to HOTH (using sandbox stack for request).

Requested changes for `ATAT Provisioning Request` flow:
- Remove `Update Portfolio to Provisioned` action from the flow
  - FYI - the `Portfolio` is updated to `Processing` in `Queue Initial Portfolio Provisioning Job` so no need to do anything with the `Portfolio`
- Update `Provisioning Job` to `In Progress` (if a successful Post) 
RequestedChanges_AT-7992

**Comment by jasonburkert-ccpo** [comment]
@juliusfitzhugh-ccpo Addressed your suggested changes in https://github.com/dod-ccpo/atat-snow/pull/175/commits/0be15d119d4459a8dd99e53611c644e6582ca8cf

Thank you for the great feedback.

image

**Review by juliusfitzhugh-ccpo — APPROVED** [review]

**Pull request merged**
